name: Build and Scan with Docker Scout

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Tag de la imagen a construir"
        required: true
        default: "latest"

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout del código
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Instalar Docker Scout (CLI plugin)
      - name: Install Docker Scout
        run: |
          curl -sSfL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh
          mkdir -p ~/.docker/cli-plugins
          mv ./bin/docker-scout ~/.docker/cli-plugins/

      # 3️⃣ Configurar variables de entorno
      - name: Set image name
        run: echo "IMAGE_NAME=myapp" >> $GITHUB_ENV

      # 4️⃣ Construir la imagen (NO push a Docker Hub)
      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          load: true
          tags: ${{ env.IMAGE_NAME }}:${{ github.event.inputs.image_tag }}

      # 5️⃣ Escanear vulnerabilidades con Docker Scout
      - name: Docker Scout analyze
        run: |
          docker scout cves ${{ env.IMAGE_NAME }}:${{ github.event.inputs.image_tag }} \
            --format json \
            --output ./scout-report.json

      # 6️⃣ Subir reporte como artefacto
      - name: Upload Scout report
        uses: actions/upload-artifact@v4
        with:
          name: scout-report
          path: ./scout-report.json
